language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

services:
  - mysql

before_script:
  - composer self-update
  - composer update
  - if [ $(phpenv version-name) != "5.6" ]; then composer require --dev phpstan/phpstan; fi

script:
  - vendor/bin/phpunit -c tests.xml
  - if [ $(phpenv version-name) != "5.6" ]; then vendor/bin/phpstan analyze -l 4 src; fi

