language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0

services:
  - mysql

before_script:
  - composer self-update
  - composer update

script:
  - composer run-script phpunit
  - composer run-script phpstan
