language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

services:
  - mysql

before_script:
  - composer self-update
  - composer --ignore-platform-reqs update

script:
  - phpunit -c tests.xml
  - if [ $(phpenv version-name) != "5.6" ]; then vendor/bin/phpstan -l 4 src; fi

